.MODEL SMALL
.STACK 100H

.DATA
MSG1 DB "ENTER FIRST NUMBER:$" 
MSG2 DB DB 0AH,0DH, "ENTER SECOND NUMBER:$"
MSG_GREATER DB 0AH,0DH, "GREATER NUMBER IS: $"
NUM1 DB ?
NUM2 DB ?

.CODE MAIN

MAIN PROC
    
    MOV AX, @DATA
    MOV DS, AX  
    
    ;PROMT FOR FIRST NUMBER
    MOV DX, OFFSET MSG1
    MOV AH, 09H
    INT 21H
    
    ;READ FIRST NUMBER
    MOV AH, 01H
    INT 21H
    SUB AL, '0'         ;CONVERT ASCI TO DECIMAL
    MOV NUM1,AL
    
    ;PROMT FOR SECOND NUMBER
    MOV DX, OFFSET MSG2
    MOV AH, 09H
    INT 21H  
    
    ;READ SECOND NUMBER 
    MOV AH, 01H
    INT 21H
    SUB AL, '0'         ;CONVERT ASCI TO DECIMAL
    MOV NUM2,AL 
    
    MOV AL, NUM1
    CMP AL, NUM2
    
    JG PRINT_NUM1   
    
PRINT_NUM2:
    MOV DX, OFFSET MSG_GREATER
    MOV AH, 09H
    INT 21H 
    
    MOV DL, NUM2
    ADD DL, '0'    ; Convert back to ASCII
    MOV AH, 02H
    INT 21H   
    
    JMP END_PROGRAM
    
PRINT_NUM1:
    MOV DX, OFFSET MSG_GREATER
    MOV AH, 09H
    INT 21H 
    
    MOV DL, NUM1
    ADD DL, '0'
    MOV AH, 02H
    INT 21H
    
    
END_PROGRAM:
    MOV AH,4CH          ;TERMINATE PROGRAM EXECUTION
    INT 21H
    
MAIN ENDP
END MAIN
     